config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :treatments
  resources :appointments
  resources :shareds
  resources :exams
  devise_for :users
  resources :users, except: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy"
      get "/search", to: "search#index"
    end

    unauthenticated do
      root "devise/registrations#new", as: :unauthenticated_root
      get "about", to: "home#about"
    end
  end

  root "home#index"
end

app/models/treatment.rb
# == Schema Information
#
# Table name: treatments
#
#  id          :bigint           not null, primary key
#  user_id     :bigint           not null
#  title       :string
#  description :text
#  date        :datetime
#  local       :string
#  kind        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Treatment < ApplicationRecord
  belongs_to :user
  has_many :tag_kinds, as: :tagable, dependent: :destroy
  has_many :tags, through: :tag_kinds
  has_many_attached :files

  enum kind: {medicamento: 0, cirurgia: 1, terapia: 2, alternativo: 3}

  validates :title, :description, :date, :local, :kind, presence: true

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  include Permissions
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]
  before_action :initial_collections, only: [:show, :new, :edit, :create, :update]

  # GET /treatments
  # GET /treatments.json
  def index
    if current_user.admin?
      @treatments = Treatment.all
    else
      professional_list = Treatment.where(user: @list).pluck(:id)
      user_list = Treatment.where(user: current_user).pluck(:id)
      @treatments = Treatment.where(id: [professional_list, user_list].flatten)
    end
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = current_user.treatments.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      professional_list = Treatment.where(user: @list).pluck(:id)
      user_list = Treatment.where(user: current_user).pluck(:id)
      treatments = Treatment.where(id: [professional_list, user_list].flatten)
      if treatments.blank?
        @treatment = nil
        redirect_to root_url, notice: "Registro não encontrado"
      else
        @treatment = Treatment.find(params[:id])
      end
    end

    def initial_collections
      @tags = Tag.all.order(:content)
    end

    # Only allow a list of trusted parameters through.
    def treatment_params
      params.require(:treatment).permit(:title, :description, :date, :local, :kind, files: [], :tag_ids=>[])
    end
end

app/views/treatments/_form.html.erb
<%= javascript_include_tag "form.js" %>

<%= simple_form_for(@treatment) do |form| %>
  <%= display_flash_messages_object(@treatment) %>
  <div class="card-body">
    <div class="form-group">
      <%= form.text_field :title, placeholder: "Título", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.text_area :description, placeholder: "Descrição", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.datetime_field :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.text_field :local, placeholder: "Local do tratamento", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.select :kind, Treatment.kinds.keys.map {|kind| [kind.titleize,kind]}, {}, { title: "Selecione o tipo de tratamento" ,class: "form-control selectpicker", data: { style: "btn btn-link" } } %>
    </div>

     <div class="form-group">
       <%= form.select :tag_ids, @tags.map{|tag| [tag.content, tag.id] }, { selected: treatment.tags.ids }, { title: "Selecione uma tag" , multiple: true, class: "form-control selectpicker", data: { style: "btn btn-link" } } %>
     </div>

    <div class="form-group form-file-upload form-file-multiple">
      <%= form.file_field :files, multiple: true, class: "file-upload" %>
      <div class="input-group">
        <input type="text" class="form-control input-name-files" placeholder="Anexos">
        <span class="input-group-btn">
          <label for="treatment_files" class="btn btn-fab btn-round btn-primary">
            <i class="material-icons">attach_file</i>
            <div class="ripple-container"></div>
          </label>
        </span>
      </div>
    </div>

    <%= form.submit class: "btn btn-primary float-right mr-3 my-4" %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Editar Tratamento</h4>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to treatments_path, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>

  <%= render 'form', treatment: @treatment %>
</div>

app/views/treatments/index.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Tratamentos</h4>
    </div>
  </div>
  <div class="card-body">
    <% if @treatments.any? %>
      <table class="table table-hover table-respoonsive">
        <thead>
          <tr>
            <% if current_user.admin? %>
              <th>Usuário</th>
            <% end %>
            <th>Título</th>
            <th>Data</th>
            <th>Local</th>
            <th>Tipo</th>
            <th>Tags</th>
            <th class="text-right">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @treatments.each do |treatment| %>
            <tr>
              <% if current_user.admin? %>
                <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>"><%= treatment.user.email %></td>
              <% end %>
              <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>"><%= treatment.title %></a></td>
              <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>"><%= date_format treatment.date %></td>
              <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>"><%= treatment.local %></td>
              <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>"><%= treatment.kind.capitalize %></td>
              <td class="linkable cursor-pointer" data-url="<%= treatment_path(treatment.id) %>">
                <%= treatment.tags.pluck(:content).to_sentence %>
              </td>
              <td class="td-actions text-right">
                <%= link_to edit_treatment_path(treatment), class: "btn btn-success", title: "Editar" do %>
                  <i class="material-icons">edit</i>
                <% end %>
                <%= link_to treatment, method: :delete, data: { confirm: 'Deseja realmente excluir?' }, title: "Excluir", class: "btn btn-danger" do %>
                  <i class="material-icons">close</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-info mt-2">
        Nenhum tratamento cadastrado.
      </div>
    <% end %>
  </div>
</div>

<%= link_to new_treatment_path, class: "btn btn-primary btn-just-icon btn-action-add btn-round btn-lg", title: "Novo tratamento" do %>
  <i class="material-icons">add</i>
<% end %>

<%= render 'layouts/modal', modal_title: "Tratamentos" %>

app/views/treatments/new.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Novo Tratamento</h4>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to treatments_path, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>

  <%= render 'form', treatment: @treatment %>
</div>

app/views/treatments/show.html.erb
<div class="card">
  <div class="card-header card-header-icon card-header-primary">
    <div class="card-icon">
      <i class="material-icons">medical_services</i>
      <span class="text-hedar">Tratamento</span>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to :back, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= @treatment.title %></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%= @treatment.kind %></h6>
    <p class="card-text"><%= @treatment.description %></p>
    <h4 class="card-title">Tags:</h4>
    <% @treatment.tags.each do |tag| %>
      <p class="card-text"><%= tag.content %></p>
    <% end %>
    <p class="card-text">Anexos: </p>

    <% if @treatment.files.any? %>
      <% @treatment.files.each do |file| %>
      <%= link_to file.filename, url_for(file), class: "card-link" %>
      <% end %>
    <% else %>
        <p class="card-text italic">Não há arquivos para este tratamento</p>
    <% end %>
  </div>

  <div class="card-footer">
    <div class="stats">
      <i class="material-icons font-icon">access_time</i>
      <%= @treatment.date.strftime("%d/%m/%Y - %H:%M") %>
    </div>
    <div class="stats">
      <i class="material-icons font-icon">location_on</i>
      <%= @treatment.local %>
    </div>
  </div>
</div>