config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :treatments
  resources :appointments
  resources :shareds
  resources :exams
  devise_for :users
  resources :users, except: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy"
      get "/search", to: "search#index"
    end

    unauthenticated do
      root "devise/registrations#new", as: :unauthenticated_root
      get "about", to: "home#about"
    end
  end

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_load_and_authorize_resource
  skip_before_action :authenticate_user!, only: [:about]

  def index
    if current_user.admin?
      @appointments = Appointment.order(:created_at).limit(3).reverse()
      @exams = Exam.order(:created_at).limit(3).reverse()
      @treatments = Treatment.order(:created_at).limit(3).reverse()
    else
      @appointments = current_user.appointments.order(:created_at).limit(3).reverse()
      @exams = current_user.exams.order(:created_at).limit(3).reverse()
      @treatments = current_user.treatments.order(:created_at).limit(3).reverse()
    end
  end

  def about
    render layout: "devise"
  end
end

app/views/home/about.html.erb
<div class="col-md-7">
<h2 class="font-weight-bold">Health History</h2>
  <h4 class="font-weight-bold">Já pensou em ter todos os seus exames, consultas e receitas em um só lugar?</h4>
  <h4 class="font-weight-bold">Com o Health History você pode, e ainda vai além.</h4>
  <h4 class="font-weight-bold">Com ele você gerencia tudo isso de forma fácil e segura e ajuda a ter o melhor diagnóstico possível.</h4>
</div>

app/views/home/index.html.erb
<div class="card card-nav-tabs">
  <div class="card-header card-header-primary">
    <i class="material-icons icon-sm">history_edu</i>
    <% if current_user.admin? %>
      <span class="card-header-text">Históricos</span>
    <% else %>
      <span class="card-header-text">Meu Histórico</span>
    <% end %>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <div class="card card-nav-tabs">
          <div class="card-header card-header-primary">
            <i class="material-icons icon-sm">local_library</i>
            <span class="card-header-text">Consultas</span>
          </div>
          <div class="card-body">
            <% if @appointments.any? %>
              <% @appointments.each do |appointment| %>
                <div class="card linkable cursor-pointer card-select" data-url="<%= appointment_path(appointment.id) %>">
                  <div class="card-body">
                    <h5 class="card-category card-category-social">
                      <i class="material-icons">local_library</i>
                      <%= appointment.title %>
                    </h5>
                    <h4 class="card-title">
                      <%= appointment.description.truncate(50) %>
                    </h4>

                    <div class="card-stats">
                      <% if current_user.admin? %>
                        <span><%= appointment.user.email %></span>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-footer justify-content-start">
                    <i class="material-icons icon-sm">calendar_today</i>
                    <span class="text-stats">
                      <%= appointment.date.strftime("%d/%m/%Y") %>
                    </span>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="alert alert-info mt-2">
                Nenhuma consulta cadastrada.
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card card-nav-tabs">
          <div class="card-header card-header-primary">
            <i class="material-icons">content_paste</i>
            <span class="card-header-text">Exames</span>
          </div>
          <div class="card-body">
            <% if @exams.any? %>
              <% @exams.each do |exam| %>
                <div class="card linkable cursor-pointer card-select" data-url="<%= exam_path(exam.id) %>">
                  <div class="card-body">
                    <h5 class="card-category card-category-social">
                      <i class="material-icons">content_paste</i>
                      <%= exam.title %>
                    </h5>
                    <h4 class="card-title">
                      <%= exam.description.truncate(50) %>
                    </h4>

                    <div class="card-stats">
                      <% if current_user.admin? %>
                        <span><%= exam.user.email %></span>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-footer justify-content-start">
                    <i class="material-icons icon-sm">calendar_today</i>
                    <span class="text-stats">
                      <%= exam.exam_date.strftime("%d/%m/%Y") %>
                    </span>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="alert alert-info mt-2">
                Nenhum exame cadastrado.
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card card-nav-tabs">
          <div class="card-header card-header-primary">
            <i class="material-icons">medical_services</i>
            <span class="card-header-text">Tratamentos</span>
          </div>
          <div class="card-body">
            <% if @treatments.any? %>
              <% @treatments.each do |treatment| %>
                <div class="card linkable cursor-pointer card-select" data-url="<%= treatment_path(treatment.id) %>">
                  <div class="card-body">
                    <h5 class="card-category card-category-social">
                      <i class="material-icons">medical_services</i>
                      <%= treatment.title %>
                    </h5>
                    <h4 class="card-title">
                      <%= treatment.description.truncate(50) %>
                    </h4>

                    <div class="card-stats">
                      <% if current_user.admin? %>
                        <span><%= treatment.user.email %></span>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-footer justify-content-start">
                    <i class="material-icons icon-sm">calendar_today</i>
                    <span class="text-stats">
                      <%= treatment.date.strftime("%d/%m/%Y") %>
                    </span>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="alert alert-info mt-2">
                Nenhum tratamento cadastrado.
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to new_shared_path, class: "btn btn-primary btn-just-icon btn-action-add btn-round btn-lg", title: "Novo compartilhamento" do %>
  <i class="material-icons">add</i>
<% end %>