config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :treatments
  resources :appointments
  resources :shareds
  resources :exams
  devise_for :users
  resources :users, except: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy"
      get "/search", to: "search#index"
    end

    unauthenticated do
      root "devise/registrations#new", as: :unauthenticated_root
      get "about", to: "home#about"
    end
  end

  root "home#index"
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  validates :content, presence: true
  has_many :tag_kinds
  has_many :treatments, through: :tag_kinds, source: :tagable, source_type: 'Treatment'
  has_many :appointments, through: :tag_kinds, source: :tagable, source_type: 'Appointment'
  has_many :exams, through: :tag_kinds, source: :tagable, source_type: 'Exam'
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:content)
    end
end

app/views/tags/_form.html.erb
<%= javascript_include_tag "form.js" %>

<%= form_with(model: tag, local: true) do |form| %>
  <%= display_flash_messages_object(@tag) %>
  <div class="card-body">
    <div class="form-group">
      <%= form.text_field :content, placeholder: "Título", class: "form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary float-right mr-3 my-4" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Editar Tag</h4>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to tags_path, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>

  <%= render 'form', tag: @tag %>
</div>

app/views/tags/index.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Tags</h4>
    </div>
  </div>
  <div class="card-body">
    <% if @tags.any? %>
      <table class="table table-hover table-respoonsive">
        <thead>
          <tr>
            <th>Título</th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td class="linkable cursor-pointer" data-url="<%= tag_path(tag.id) %>"><%= tag.content %></a></td>
              <td class="td-actions text-right">
                <%= link_to edit_tag_path(tag), class: "btn btn-success", title: "Editar" do %>
                  <i class="material-icons">edit</i>
                <% end %>
                <%= link_to tag, method: :delete, data: { confirm: 'Deseja realmente excluir?' }, title: "Excluir", class: "btn btn-danger" do %>
                  <i class="material-icons">close</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-info mt-2">
        Nenhuma tag cadastrada.
      </div>
    <% end %>
  </div>
</div>

<%= link_to new_tag_path, class: "btn btn-primary btn-just-icon btn-action-add btn-round btn-lg", title: "Nova tag" do %>
  <i class="material-icons">add</i>
<% end %>

app/views/tags/new.html.erb
<div class="card">
  <div class="card-header card-header-text card-header-primary">
    <div class="card-text">
      <h4 class="card-title">Nova tag</h4>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to  tags_path, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>

  <%= render 'form', tag: @tag %>
</div>

app/views/tags/show.html.erb
<div class="card">
  <div class="card-header card-header-icon card-header-primary">
    <div class="card-icon">
      <i class="material-icons">person</i>
      <span class="text-hedar">Tag</span>
    </div>

    <div class="card-text float-right rounded-30 p-2">
      <%= link_to tags_path, class: "text-white", title: "Voltar" do %>
        <i class="material-icons">keyboard_backspace</i>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= @tag.content %></h4>
  </div>
</div>