config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :treatments
  resources :appointments
  resources :shareds
  resources :exams
  devise_for :users
  resources :users, except: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy"
      get "/search", to: "search#index"
    end

    unauthenticated do
      root "devise/registrations#new", as: :unauthenticated_root
      get "about", to: "home#about"
    end
  end

  root "home#index"
end

app/views/layouts/_modal.html.erb
<div class="modal fade" id="share-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= modal_title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <%= form_with(model: Shared, local: true) do |form| %>
        <div class="form-group">
          <label for="">Compartilhar com</label>
          <%= form.select :user_id, User.all.pluck(:email, :id), { prompt: "Selecione o usuário" }, { class: 'form-control' } %>
        </div>
      <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Compartilhar</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_lateral.html.erb
<div class="sidebar sidebar-lateral-left" id="sidebar-lateral">
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="material-icons">history_edu</i>
          <% if current_user.admin? %>
            <p>Históricos</p>
          <% else %>
            <p>Meu histórico</p>
          <% end %>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= shareds_path %>">
          <i class="material-icons">share</i>
          <p>Históricos compartilhados</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= exams_path %>">
          <i class="material-icons">content_paste</i>
          <p>Exames</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= treatments_path %>">
          <i class="material-icons">medical_services</i>
          <p>Tratamentos</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= appointments_path %>">
          <i class="material-icons">local_library</i>
          <p>Consultas</p>
        </a>
      </li>
      <% if current_user.admin? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= tags_path %>">
            <i class="material-icons">check</i>
            <p>Criar tags</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= users_path %>">
            <i class="material-icons">person</i>
            <p>Usuários</p>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/sidebar_lateral' %>
    <nav class="navbar navbar-expand-lg bg-primary fixed-top">
      <div class="container-fluid">
        <div class="btn btn-primary btn-just-icon btn-round btn-lg toggle-menu">
          <i class="material-icons">menu</i>
        </div>
        <a class="navbar-brand" href="<%= root_path %>">Health History</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <%= form_with(url: search_path, local: true, method: :get, class: "form-inline ml-auto has-white") do |form| %>
              <div class="form-group no-border bmd-form-group">
                <%= form.text_field :title, class: "form-control", placeholder: "Pesquisar", required: true %>
              </div>
              <button type="submit" class="btn btn-neutral btn-icon btn-round btn-primary">
                <i class="material-icons">search</i>
              </button>
            <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" title="<%= current_user.email.split("@")[0] %>" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">person</i>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                <a class="dropdown-item" href="/users/<%= current_user.id %>">Perfil</a>
                <div class="dropdown-divider"></div>
                <%= link_to('Sair', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container padding-top-6">
      <%= display_flash_messages %>
      <%= yield %>
      <%= yield :javascript_includes %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-body">
    <nav class="navbar navbar-expand-lg bg-primary fixed-top">
      <div class="container-fluid">
        <img src="<%= asset_path 'logo2.png' %>" alt="logo" height="55rem">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Sobre', about_path(route: :about), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if params[:route] == "sign_in" %>
                <a class="nav-link" href="/users/sign_up?route=sign_up">Criar conta<div class="ripple-container"></div></a>
              <% else %>
                <a class="nav-link" href="/users/sign_in?route=sign_in">Entrar<div class="ripple-container"></div></a>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= display_flash_messages_devise %>
      <div class="row vertical-center">
        <% if params[:route] != "about" %>
          <div class="col-md-7">
            <h1 class="text-center font-weight-bold">
              <span>Bem vindo ao</span><br>
              <span>Health History</span>
            </h1>
            <h4 class="text-center">Aqui seus exames e históricos médicos</h4>
            <h4 class="text-center">ficam a sua disposição</h4>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>